### ISSUE TITLE
Lanterns not giving off light

### ISSUE THREAD

**Issue by SleepingDragon969** [RebelKeithy/Metallurgy3#23]
The lanterns in Metallurgy 3.6.1 are not giving off any light source. I have tried both making them and using Too many items to create them but to no avail. I am using Optifine HD B1, Forge 608 and multiple mods to include Harkenscythe w/ hallowed, asgard shield and nether ender add ons. I am also using iron chest, enchanting plus, special armor, twilight forest, Zans mini map and of course the newest edition of Metallurgy. If anyone else is having this problem please let me know so i can tell if it is one of my mods and Rebel, if it isn't please fix this issue because I really need those lanterns to work to complete my castle of the Gods...lol.

**Comment by Vyrebird** [comment]
The lantern's don't give off light for me either (tested in 3.0.0.0.6.1).

They don't appear to ever be set as lightsources -  so the fix is probably just to call Block's setLightValue(float) on them at some point.  The M2 lanterns appeared to be level 15 lightsources, like pumpkin lanterns, so that'd be setLightValue(1.0F).

**Comment by SleepingDragon969** [comment]
Well its good to know its not my mods causing the issue. Thank you for your help, I hope it gets a fix soon as I don't have the software to alter the light value.

**Comment by RebelKeithy** [comment]
Yup, that's the problem. Fixed
